name: Production Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Execute SSH commmands
      uses: JimCronqvist/action-ssh@0.1.1
      with:
        hosts: ${{ secrets.SSH_HOST }}
        privateKey: ${{ secrets.PRIVATE_KEY }}
        command: |
          cd /var/www/0xffff-env/wwwroot
          git pull --recurse-submodules
          git submodule update --init --recursive
          docker run --rm --volume $PWD:/app --user $(id -u):$(id -g) composer i --ignore-platform-reqs -vvv
          docker run --rm --volume $PWD:/app --user $(id -u):$(id -g) composer dump-autoload -o
          echo "clear cache..."
          rm -f public/assets/admin-* public/assets/forum-* public/assets/rev-manifest.json
