name: Production Deployment

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Execute SSH commmands
      uses: JimCronqvist/action-ssh@0.1.1
      with:
        hosts: ${{ secrets.PRIVATE_KEY }}
        privateKey: ${{ secrets.PRIVATE_KEY }}
        command: |
          cd /var/www/0xffff-env/wwwroot
          git pull --recurse-submodules
          git submodule update --init --recursive
          docker run --rm -v $(pwd):/var/www geshan/php-composer-alpine "composer i --ignore-platform-reqs -vvv"
          docker run --rm -v $(pwd):/var/www geshan/php-composer-alpine "composer dump-autoload -o"
          rm -f public/assets/admin-* public/assets/forum-* public/assets/rev-manifest.json
